# Generated by Django 5.1.1 on 2024-10-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_yemconsulting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='quantites_initiales',
            field=models.JSONField(default=dict),
        ),
    ]
