# Generated by Django 5.2 on 2025-05-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_yemconsulting', '0002_utilisateur_code_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_inscription',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='adresse_facturation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse facturation'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_postal_facturation',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code postal facturation'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='complement_adresse_facturation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Complément facturation'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='pays_facturation',
            field=models.CharField(default='Belgique', max_length=100, verbose_name='Pays facturation'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ville_facturation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville facturation'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse email'),
        ),
    ]
