# Generated by Django 5.2 on 2025-05-03 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_yemconsulting', '0003_remove_utilisateur_date_inscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('shipping', 'Adresse de livraison'), ('billing', 'Adresse de facturation')], max_length=10)),
                ('adresse', models.CharField(max_length=255)),
                ('complement', models.CharField(blank=True, max_length=255)),
                ('code_postal', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Belgique', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Adresse par défaut pour ce type')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'type', 'is_default')},
            },
        ),
    ]
