# Generated by Django 5.1.1 on 2025-02-09 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_yemconsulting', '0003_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignepanier',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_yemconsulting.produit'),
        ),
        migrations.AlterField(
            model_name='lignepanier',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
