# Generated by Django 5.2 on 2025-05-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_yemconsulting', '0005_alter_adresse_options_alter_adresse_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adresse',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
