# Generated by Django 5.2 on 2025-05-04 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_yemconsulting', '0007_migrate_adresse_prenom_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='active',
            field=models.BooleanField(default=True, help_text="Indique si l'adresse est active"),
        ),
        migrations.AddField(
            model_name='commande',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='app_yemconsulting.adresse'),
        ),
    ]
