# Generated by Django 5.2 on 2025-05-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_yemconsulting', '0010_convert_quantites_initiales_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='livraison',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix de la livraison', max_digits=10),
        ),
    ]
