# Generated by Django 5.2 on 2025-05-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_yemconsulting', '0012_remove_commande_address_commande_adresse_facturation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='adresse_facturation',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='code_postal_facturation',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='complement_adresse',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='complement_adresse_facturation',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='pays_facturation',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='societe',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='ville_facturation',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
