# Generated by Django 5.2 on 2025-05-13 11:58

from django.db import migrations

def create_default_category(apps, schema_editor):
    Categorie = apps.get_model('app_yemconsulting', 'Categorie')
    Produit = apps.get_model('app_yemconsulting', 'Produit')
    
    # Créer la catégorie par défaut
    categorie_default = Categorie.objects.create(nom="Non classé")
    
    # Mettre à jour tous les produits sans catégorie
    Produit.objects.filter(categorie__isnull=True).update(categorie=categorie_default)

class Migration(migrations.Migration):

    dependencies = [
        ('app_yemconsulting', '0013_supprimer_champs_utilisateur'),
    ]

    operations = [
        migrations.RunPython(create_default_category),
        migrations.RemoveField(
            model_name='adresse',
            name='active',
        ),
    ]
