# Generated by Django 5.2 on 2025-05-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_yemconsulting', '0018_remove_commande_panier_remove_commande_traitée_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="Adresse supprimée par l'utilisateur"),
        ),
    ]
